# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Armadactl < Formula
  desc "Example binary distribution using homebrew"
  homepage "https://github.com/ljubon/homebrew-armadactl"
  version "0.3.94"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ljubon/armada/releases/download/v0.3.94/armadactl_0.3.94_darwin_amd64.tar.gz"
      sha256 "55198b582e937ca29853d8be263c17b8f55f08b85519befa9e42568c2e35bf57"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ljubon/armada/releases/download/v0.3.94/armadactl_0.3.94_darwin_arm64.tar.gz"
      sha256 "bb5a609e4a5db2f19aee326f99e44c80f49065167f23c9ad9369ca83527e87da"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ljubon/armada/releases/download/v0.3.94/armadactl_0.3.94_linux_amd64.tar.gz"
      sha256 "5dd78436535da646041b851e76020f17698e235a760c3e994119b8727fb83238"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljubon/armada/releases/download/v0.3.94/armadactl_0.3.94_linux_arm64.tar.gz"
      sha256 "cb9a5734a75774f06521d0ef70da5ecdfa83db4b8d1edf9f1c9cdc38398a31bd"
    end
  end

  def install
    bin.install "armadactl"
  end

  test do
    system "#{bin}/armadactl help"
  end
end
