# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Armadactl < Formula
  desc "Example binary distribution using homebrew"
  homepage "https://github.com/ljubon/homebrew-armadactl"
  version "0.3.96"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ljubon/armada/releases/download/v0.3.96/armadactl_0.3.96_darwin_amd64.tar.gz"
      sha256 "f712628266c17ee37c41835814a4832c12d82a228bf3e2c31d10daebcb8cd127"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ljubon/armada/releases/download/v0.3.96/armadactl_0.3.96_darwin_arm64.tar.gz"
      sha256 "ab8e98cb59be46c95a301f3eb0fe41bd1ef2b65981ba60070043ba47f15968ee"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ljubon/armada/releases/download/v0.3.96/armadactl_0.3.96_linux_amd64.tar.gz"
      sha256 "281ddb35d32d7f9bae8d927176587f2f8614167b64c8777d9433493a9b04e4e1"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ljubon/armada/releases/download/v0.3.96/armadactl_0.3.96_linux_arm64.tar.gz"
      sha256 "28adf8363eb8b6d425f3ea5fcdd84ab8fc59ede9154e7c9975e4eda367869cf0"
    end
  end

  def install
    bin.install "armadactl"
  end

  test do
    system "#{bin}/armadactl help"
  end
end
